name: Deploy to DigitalOcean (root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Check if the secret is actually loading
          if [ -z "${{ secrets.DROPLET_IP }}" ]; then
            echo "Error: DROPLET_IP secret is empty"
            exit 1
          fi
          
          echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -v -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
          

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 root@${{ secrets.DROPLET_IP }} << 'EOF'   
           set -e
            cd ~/Food-price-Cambodia-dashboard
            git reset --hard
            git clean -fd
            git fetch origin main
            git reset --hard origin/main            
            npm install -g pm2
            npm run build || true
            pm2 restart myapp
            pm2 save

          EOF
